/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedVehiclesIndexRouteImport } from './routes/_authenticated/vehicles/index'
import { Route as AuthenticatedTodayIndexRouteImport } from './routes/_authenticated/today/index'
import { Route as AuthenticatedSearchIndexRouteImport } from './routes/_authenticated/search/index'
import { Route as AuthenticatedReviewQueueIndexRouteImport } from './routes/_authenticated/review-queue/index'
import { Route as AuthenticatedJobsIndexRouteImport } from './routes/_authenticated/jobs/index'
import { Route as AuthenticatedInvoicesIndexRouteImport } from './routes/_authenticated/invoices/index'
import { Route as AuthenticatedDocumentsIndexRouteImport } from './routes/_authenticated/documents/index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers/index'
import { Route as AuthenticatedClaimsIndexRouteImport } from './routes/_authenticated/claims/index'
import { Route as AuthenticatedAssistantIndexRouteImport } from './routes/_authenticated/assistant/index'
import { Route as AuthenticatedVehiclesVehicleIdRouteImport } from './routes/_authenticated/vehicles/$vehicleId'
import { Route as AuthenticatedMIntakeRouteImport } from './routes/_authenticated/m/intake'
import { Route as AuthenticatedJobsNewRouteImport } from './routes/_authenticated/jobs/new'
import { Route as AuthenticatedJobsJobIdRouteImport } from './routes/_authenticated/jobs/$jobId'
import { Route as AuthenticatedDocumentsArchiveRouteImport } from './routes/_authenticated/documents/archive'
import { Route as AuthenticatedDocumentsDocIdRouteImport } from './routes/_authenticated/documents/$docId'
import { Route as AuthenticatedCustomersCustomerIdRouteImport } from './routes/_authenticated/customers/$customerId'
import { Route as AuthenticatedClaimsTemplatesRouteImport } from './routes/_authenticated/claims/templates'
import { Route as AuthenticatedClaimsFillJobIdRouteImport } from './routes/_authenticated/claims/fill.$jobId'

const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVehiclesIndexRoute =
  AuthenticatedVehiclesIndexRouteImport.update({
    id: '/vehicles/',
    path: '/vehicles/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTodayIndexRoute = AuthenticatedTodayIndexRouteImport.update({
  id: '/today/',
  path: '/today/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchIndexRoute =
  AuthenticatedSearchIndexRouteImport.update({
    id: '/search/',
    path: '/search/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReviewQueueIndexRoute =
  AuthenticatedReviewQueueIndexRouteImport.update({
    id: '/review-queue/',
    path: '/review-queue/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJobsIndexRoute = AuthenticatedJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesIndexRoute =
  AuthenticatedInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsIndexRoute =
  AuthenticatedDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClaimsIndexRoute =
  AuthenticatedClaimsIndexRouteImport.update({
    id: '/claims/',
    path: '/claims/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssistantIndexRoute =
  AuthenticatedAssistantIndexRouteImport.update({
    id: '/assistant/',
    path: '/assistant/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVehiclesVehicleIdRoute =
  AuthenticatedVehiclesVehicleIdRouteImport.update({
    id: '/vehicles/$vehicleId',
    path: '/vehicles/$vehicleId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMIntakeRoute = AuthenticatedMIntakeRouteImport.update({
  id: '/m/intake',
  path: '/m/intake',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsNewRoute = AuthenticatedJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsJobIdRoute = AuthenticatedJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsArchiveRoute =
  AuthenticatedDocumentsArchiveRouteImport.update({
    id: '/documents/archive',
    path: '/documents/archive',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsDocIdRoute =
  AuthenticatedDocumentsDocIdRouteImport.update({
    id: '/documents/$docId',
    path: '/documents/$docId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersCustomerIdRoute =
  AuthenticatedCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClaimsTemplatesRoute =
  AuthenticatedClaimsTemplatesRouteImport.update({
    id: '/claims/templates',
    path: '/claims/templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClaimsFillJobIdRoute =
  AuthenticatedClaimsFillJobIdRouteImport.update({
    id: '/claims/fill/$jobId',
    path: '/claims/fill/$jobId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/update-password': typeof UpdatePasswordRoute
  '/claims/templates': typeof AuthenticatedClaimsTemplatesRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/documents/$docId': typeof AuthenticatedDocumentsDocIdRoute
  '/documents/archive': typeof AuthenticatedDocumentsArchiveRoute
  '/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/jobs/new': typeof AuthenticatedJobsNewRoute
  '/m/intake': typeof AuthenticatedMIntakeRoute
  '/vehicles/$vehicleId': typeof AuthenticatedVehiclesVehicleIdRoute
  '/assistant/': typeof AuthenticatedAssistantIndexRoute
  '/claims/': typeof AuthenticatedClaimsIndexRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/jobs/': typeof AuthenticatedJobsIndexRoute
  '/review-queue/': typeof AuthenticatedReviewQueueIndexRoute
  '/search/': typeof AuthenticatedSearchIndexRoute
  '/today/': typeof AuthenticatedTodayIndexRoute
  '/vehicles/': typeof AuthenticatedVehiclesIndexRoute
  '/claims/fill/$jobId': typeof AuthenticatedClaimsFillJobIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/update-password': typeof UpdatePasswordRoute
  '/': typeof AuthenticatedIndexRoute
  '/claims/templates': typeof AuthenticatedClaimsTemplatesRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/documents/$docId': typeof AuthenticatedDocumentsDocIdRoute
  '/documents/archive': typeof AuthenticatedDocumentsArchiveRoute
  '/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/jobs/new': typeof AuthenticatedJobsNewRoute
  '/m/intake': typeof AuthenticatedMIntakeRoute
  '/vehicles/$vehicleId': typeof AuthenticatedVehiclesVehicleIdRoute
  '/assistant': typeof AuthenticatedAssistantIndexRoute
  '/claims': typeof AuthenticatedClaimsIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/documents': typeof AuthenticatedDocumentsIndexRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
  '/jobs': typeof AuthenticatedJobsIndexRoute
  '/review-queue': typeof AuthenticatedReviewQueueIndexRoute
  '/search': typeof AuthenticatedSearchIndexRoute
  '/today': typeof AuthenticatedTodayIndexRoute
  '/vehicles': typeof AuthenticatedVehiclesIndexRoute
  '/claims/fill/$jobId': typeof AuthenticatedClaimsFillJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/update-password': typeof UpdatePasswordRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/claims/templates': typeof AuthenticatedClaimsTemplatesRoute
  '/_authenticated/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/_authenticated/documents/$docId': typeof AuthenticatedDocumentsDocIdRoute
  '/_authenticated/documents/archive': typeof AuthenticatedDocumentsArchiveRoute
  '/_authenticated/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/_authenticated/jobs/new': typeof AuthenticatedJobsNewRoute
  '/_authenticated/m/intake': typeof AuthenticatedMIntakeRoute
  '/_authenticated/vehicles/$vehicleId': typeof AuthenticatedVehiclesVehicleIdRoute
  '/_authenticated/assistant/': typeof AuthenticatedAssistantIndexRoute
  '/_authenticated/claims/': typeof AuthenticatedClaimsIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/_authenticated/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/_authenticated/jobs/': typeof AuthenticatedJobsIndexRoute
  '/_authenticated/review-queue/': typeof AuthenticatedReviewQueueIndexRoute
  '/_authenticated/search/': typeof AuthenticatedSearchIndexRoute
  '/_authenticated/today/': typeof AuthenticatedTodayIndexRoute
  '/_authenticated/vehicles/': typeof AuthenticatedVehiclesIndexRoute
  '/_authenticated/claims/fill/$jobId': typeof AuthenticatedClaimsFillJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/update-password'
    | '/claims/templates'
    | '/customers/$customerId'
    | '/documents/$docId'
    | '/documents/archive'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/m/intake'
    | '/vehicles/$vehicleId'
    | '/assistant/'
    | '/claims/'
    | '/customers/'
    | '/documents/'
    | '/invoices/'
    | '/jobs/'
    | '/review-queue/'
    | '/search/'
    | '/today/'
    | '/vehicles/'
    | '/claims/fill/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/update-password'
    | '/'
    | '/claims/templates'
    | '/customers/$customerId'
    | '/documents/$docId'
    | '/documents/archive'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/m/intake'
    | '/vehicles/$vehicleId'
    | '/assistant'
    | '/claims'
    | '/customers'
    | '/documents'
    | '/invoices'
    | '/jobs'
    | '/review-queue'
    | '/search'
    | '/today'
    | '/vehicles'
    | '/claims/fill/$jobId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/update-password'
    | '/_authenticated/'
    | '/_authenticated/claims/templates'
    | '/_authenticated/customers/$customerId'
    | '/_authenticated/documents/$docId'
    | '/_authenticated/documents/archive'
    | '/_authenticated/jobs/$jobId'
    | '/_authenticated/jobs/new'
    | '/_authenticated/m/intake'
    | '/_authenticated/vehicles/$vehicleId'
    | '/_authenticated/assistant/'
    | '/_authenticated/claims/'
    | '/_authenticated/customers/'
    | '/_authenticated/documents/'
    | '/_authenticated/invoices/'
    | '/_authenticated/jobs/'
    | '/_authenticated/review-queue/'
    | '/_authenticated/search/'
    | '/_authenticated/today/'
    | '/_authenticated/vehicles/'
    | '/_authenticated/claims/fill/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vehicles/': {
      id: '/_authenticated/vehicles/'
      path: '/vehicles'
      fullPath: '/vehicles/'
      preLoaderRoute: typeof AuthenticatedVehiclesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/today/': {
      id: '/_authenticated/today/'
      path: '/today'
      fullPath: '/today/'
      preLoaderRoute: typeof AuthenticatedTodayIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search/': {
      id: '/_authenticated/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof AuthenticatedSearchIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/review-queue/': {
      id: '/_authenticated/review-queue/'
      path: '/review-queue'
      fullPath: '/review-queue/'
      preLoaderRoute: typeof AuthenticatedReviewQueueIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/': {
      id: '/_authenticated/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AuthenticatedJobsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/': {
      id: '/_authenticated/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthenticatedInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/': {
      id: '/_authenticated/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof AuthenticatedDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/claims/': {
      id: '/_authenticated/claims/'
      path: '/claims'
      fullPath: '/claims/'
      preLoaderRoute: typeof AuthenticatedClaimsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant/': {
      id: '/_authenticated/assistant/'
      path: '/assistant'
      fullPath: '/assistant/'
      preLoaderRoute: typeof AuthenticatedAssistantIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vehicles/$vehicleId': {
      id: '/_authenticated/vehicles/$vehicleId'
      path: '/vehicles/$vehicleId'
      fullPath: '/vehicles/$vehicleId'
      preLoaderRoute: typeof AuthenticatedVehiclesVehicleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/intake': {
      id: '/_authenticated/m/intake'
      path: '/m/intake'
      fullPath: '/m/intake'
      preLoaderRoute: typeof AuthenticatedMIntakeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/new': {
      id: '/_authenticated/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof AuthenticatedJobsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/$jobId': {
      id: '/_authenticated/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof AuthenticatedJobsJobIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/archive': {
      id: '/_authenticated/documents/archive'
      path: '/documents/archive'
      fullPath: '/documents/archive'
      preLoaderRoute: typeof AuthenticatedDocumentsArchiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/$docId': {
      id: '/_authenticated/documents/$docId'
      path: '/documents/$docId'
      fullPath: '/documents/$docId'
      preLoaderRoute: typeof AuthenticatedDocumentsDocIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/$customerId': {
      id: '/_authenticated/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/claims/templates': {
      id: '/_authenticated/claims/templates'
      path: '/claims/templates'
      fullPath: '/claims/templates'
      preLoaderRoute: typeof AuthenticatedClaimsTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/claims/fill/$jobId': {
      id: '/_authenticated/claims/fill/$jobId'
      path: '/claims/fill/$jobId'
      fullPath: '/claims/fill/$jobId'
      preLoaderRoute: typeof AuthenticatedClaimsFillJobIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedClaimsTemplatesRoute: typeof AuthenticatedClaimsTemplatesRoute
  AuthenticatedCustomersCustomerIdRoute: typeof AuthenticatedCustomersCustomerIdRoute
  AuthenticatedDocumentsDocIdRoute: typeof AuthenticatedDocumentsDocIdRoute
  AuthenticatedDocumentsArchiveRoute: typeof AuthenticatedDocumentsArchiveRoute
  AuthenticatedJobsJobIdRoute: typeof AuthenticatedJobsJobIdRoute
  AuthenticatedJobsNewRoute: typeof AuthenticatedJobsNewRoute
  AuthenticatedMIntakeRoute: typeof AuthenticatedMIntakeRoute
  AuthenticatedVehiclesVehicleIdRoute: typeof AuthenticatedVehiclesVehicleIdRoute
  AuthenticatedAssistantIndexRoute: typeof AuthenticatedAssistantIndexRoute
  AuthenticatedClaimsIndexRoute: typeof AuthenticatedClaimsIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedDocumentsIndexRoute: typeof AuthenticatedDocumentsIndexRoute
  AuthenticatedInvoicesIndexRoute: typeof AuthenticatedInvoicesIndexRoute
  AuthenticatedJobsIndexRoute: typeof AuthenticatedJobsIndexRoute
  AuthenticatedReviewQueueIndexRoute: typeof AuthenticatedReviewQueueIndexRoute
  AuthenticatedSearchIndexRoute: typeof AuthenticatedSearchIndexRoute
  AuthenticatedTodayIndexRoute: typeof AuthenticatedTodayIndexRoute
  AuthenticatedVehiclesIndexRoute: typeof AuthenticatedVehiclesIndexRoute
  AuthenticatedClaimsFillJobIdRoute: typeof AuthenticatedClaimsFillJobIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedClaimsTemplatesRoute: AuthenticatedClaimsTemplatesRoute,
  AuthenticatedCustomersCustomerIdRoute: AuthenticatedCustomersCustomerIdRoute,
  AuthenticatedDocumentsDocIdRoute: AuthenticatedDocumentsDocIdRoute,
  AuthenticatedDocumentsArchiveRoute: AuthenticatedDocumentsArchiveRoute,
  AuthenticatedJobsJobIdRoute: AuthenticatedJobsJobIdRoute,
  AuthenticatedJobsNewRoute: AuthenticatedJobsNewRoute,
  AuthenticatedMIntakeRoute: AuthenticatedMIntakeRoute,
  AuthenticatedVehiclesVehicleIdRoute: AuthenticatedVehiclesVehicleIdRoute,
  AuthenticatedAssistantIndexRoute: AuthenticatedAssistantIndexRoute,
  AuthenticatedClaimsIndexRoute: AuthenticatedClaimsIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedDocumentsIndexRoute: AuthenticatedDocumentsIndexRoute,
  AuthenticatedInvoicesIndexRoute: AuthenticatedInvoicesIndexRoute,
  AuthenticatedJobsIndexRoute: AuthenticatedJobsIndexRoute,
  AuthenticatedReviewQueueIndexRoute: AuthenticatedReviewQueueIndexRoute,
  AuthenticatedSearchIndexRoute: AuthenticatedSearchIndexRoute,
  AuthenticatedTodayIndexRoute: AuthenticatedTodayIndexRoute,
  AuthenticatedVehiclesIndexRoute: AuthenticatedVehiclesIndexRoute,
  AuthenticatedClaimsFillJobIdRoute: AuthenticatedClaimsFillJobIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
